title: <p align="center"> Kaushik Paul </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kaushik-paul-a31384169/">LinkedIn</a> |
  <a href="https://github.com/kaushikpaul34">GitHub</a>
  
  <br>   
  As a Mechanical Designer, I have basic knowledge in engineering principles, design techniques, and project management. 
  However, my passion for technology and desire to broaden my skillset led me to pursue a career change in the field of Machine Learning and AI. .

  <br>
  </p>
